### ISSUE TITLE
how an outage of the Internet is detected?

### ISSUE THREAD

**Issue by hayatbellafkih** [RIPE-Atlas-Community/ripe-atlas-halo#8]
Hello,

This project can display the outages of the Internet is some regions based on RIPE Atlas (probes and data). 
1. How these outages are detected: 
- By a log file of the probe?
-  By a long delay of one ping or traceroute?
- How distinguish user unpluged probe (so disconnected from the Internet) from a probe that is  unable to connect to Internet due to connectivity problem?

2. Are you using the built-in measurements or UDM measurements ?

Thanks.

Hayat

**Comment by danielquinn** [comment]
It's been a year since we made this for the Hackathon in Copenhagen, but I'll try to answer your questions.

Halo makes use of the RIPE Atlas API (via the [Cousteau library](https://github.com/RIPE-NCC/ripe-atlas-cousteau/)) which in turn pull that data from the results database on NCC hardware.  So-called "disconnect events" are measured by looking at the results for measurement id `7000`, which is a built-in.  As for how to tell the *nature* of the disconnect event: that's not really possible.  However, Halo doesn't alert on just one probe going down.  Instead it will alert in the event that a high number of probes within a certain region/network go down around the same time.

Much of the magic that determines the up/down nature of a probe vs. a network was coded by @shane-kerr [here](https://github.com/RIPE-Atlas-Community/ripe-atlas-halo/blob/master/src/events/models.py#L77-L89).  Have a look at that class if you're curious about more details.
